backend:
  name: github
  repo: Wangxiaoxiaoa/Wangxiaoxiaoa
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "摘要", name: "description", widget: "string", required: false }
      - { label: "封面图", name: "cover", widget: "image", required: false }
      - label: "分类"
        name: "categories"
        widget: "list"
        required: false
      - label: "标签"
        name: "tags"
        widget: "list"
        required: false
      - { label: "启用公式", name: "math", widget: "boolean", default: false, required: false }
      - { label: "内容", name: "body", widget: "markdown" }

  - name: "pages"
    label: "页面"
    folder: "content/page"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "内容", name: "body", widget: "markdown" }
